server:
  port: 8082
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://cataas-client-db:5440/cataas-client-db
    password: password
    username: username
org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true